name: inmobiliaria-andes

services:
  inmobiliaria-api:
    restart: always
    build:
      context: .
      dockerfile: DockerFile    
    env_file:
      - path: .env
        required: true
    environment:
      - DataBase__DataSource=${DATASOURCE}
      - DataBase__UserId=${USERID}
      - DataBase__Password=${PASSWORD}
      - DataBase__InitialCatalog=${INITIALCATALOG}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports:
      - 3000:5000

